### ISSUE TITLE
Add link to YouTube video?

### ISSUE THREAD

**Issue by wsvincent** [doherty-labs/health-app-demo#2]
This is a very cool project. Maybe add a link in the Readme to your [YouTube video](https://youtu.be/hZatMLtjqHs?si=nm6csM53C1jVgegy) on it? We plan to feature it in a forthcoming Django News newsletter.

**Comment by John-Doherty01** [comment]
@wsvincent Thanks for watching! Yeah sure will update Readme now. I had my notification turned off for GitHub too I should probably re-enable them again so don't miss stuff like this again lol

**Comment by wsvincent** [comment]
Awesome. We actually featured it [last week](https://django-news.com/issues/220#projects). Again, cool project and great you had a video discussing it as well.
